import {mycheckbox,checkboxmsg,checkbox1,checkbox2,checkbox3,checkbox4,AllCheckBox} from './myConst'
const x = require('./DateTime')
function mywait() {
  cy.wait(100)
}

function CheckBox_Demo(){
  cy.contains('Input Forms').click()
  mywait()
  cy.contains('Checkbox Demo').click()
  mywait()
  cy.request('https://demo.seleniumeasy.com/basic-checkbox-demo.html').then((response) => {
    expect(response.status).to.eq(200)
  })
  mywait()
  cy.get(mycheckbox).should('be.visible')
  cy.get(mycheckbox).check()
  mywait()
  cy.get(checkboxmsg).contains('Success - Check box is checked')
  mywait()
  cy.get(mycheckbox).uncheck()
  mywait()
  cy.get(checkboxmsg).should('not.have.value')
  mywait()
  cy.get(checkbox1).should('not.be.checked')
  mywait()
  cy.get(checkbox2).should('not.be.checked')
  mywait()
  cy.get(checkbox3).should('not.be.checked')
  mywait()
  cy.get(checkbox4).should('not.be.checked')
  mywait()
  cy.get(AllCheckBox).click()
  mywait()
  cy.get(checkbox1).should('be.checked')
  mywait()
  cy.get(checkbox2).should('be.checked')
  mywait()
  cy.get(checkbox3).should('be.checked')
  mywait()
  cy.get(checkbox4).should('be.checked')
  mywait()
  cy.get(AllCheckBox).click()
  mywait()
  cy.get(checkbox1).should('not.be.checked')
  mywait()
  cy.get(checkbox2).should('not.be.checked')
  mywait()
  cy.get(checkbox3).should('not.be.checked')
  mywait()
  cy.get(checkbox4).should('not.be.checked')
  mywait()
  cy.writeFile('cypress/integration/testResults.txt', x.myDateTime() + ' '+'CheckBox_Demo passed'+'\n', { flag: 'a+' })
}
module.exports={CheckBox_Demo}