import {taskSearch,userFilter,userNumber,userName, userFirstName,userLastName} from './myConst'

const x = require('./DateTime')

function mywait() {
    cy.wait(100)
}

function Table_Data_Search(){
    cy.contains('Table').click()
    mywait()
    cy.contains('Table Data Search').click()
    mywait()
    cy.request('https://demo.seleniumeasy.com/table-search-filter-demo.html').then((response) => {expect(response.status).to.eq(200)})
    mywait()
    cy.get(taskSearch).should('be.empty')
    cy.get(taskSearch).type('Philadelphia')
    mywait()
    cy.get(taskSearch).clear()
    mywait()
    cy.get(taskSearch).type('Browser Issues')
    mywait()
    cy.get(taskSearch).clear()
    mywait()
    cy.get(taskSearch).type('John')
    mywait()
    cy.get(taskSearch).clear()
    mywait()
    cy.get(taskSearch).type('in progress')
    mywait()
    cy.get(taskSearch).clear()
    mywait()
    cy.get(userNumber).should('be.disabled')
    cy.get(userName).should('be.disabled')
    cy.get(userFirstName).should('be.disabled')
    cy.get(userLastName).should('be.disabled')
    cy.get(userFilter).click()
    mywait()
    cy.get(userNumber).should('be.enabled')
    cy.get(userName).should('be.enabled')
    cy.get(userFirstName).should('be.enabled')
    cy.get(userLastName).should('be.enabled')
    mywait()
    cy.get(userNumber).type('8')
    mywait()
    cy.get(userNumber).clear()
    mywait()
    cy.get(userNumber).type('3')
    mywait()
    cy.get(userNumber).clear()
    mywait()
    cy.get(userName).type('larryphila')
    mywait()
    cy.get(userName).clear()
    mywait()
    cy.get(userName).type('jacobs')
    mywait()
    cy.get(userName).clear()
    mywait()
    cy.get(userFirstName).type('Ron')
    mywait()
    cy.get(userFirstName).clear()
    mywait()
    cy.get(userFirstName).type('Daniel')
    mywait()
    cy.get(userFirstName).clear()
    mywait()
    cy.get(userLastName).type('Roberts')
    mywait()
    cy.get(userLastName).clear()
    mywait()
    cy.get(userLastName).type('Karano')
    mywait()
    cy.get(userLastName).clear()
    mywait()
    cy.writeFile('cypress/integration/testResults.txt', x.myDateTime() + ' '+'Table_Data_Search passed'+'\n', { flag: 'a+' })
}
module.exports = {Table_Data_Search}